
export  const REGISTER_START = "REGISTER_START";
export  const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export  const REGISTER_FAIL = "REGISTER_FAIL";

export  const LOGIN_START = "LOGIN_START";
export  const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export  const LOGIN_FAIL = "LOGIN_FAIL";

export  const LOGOUT_START = "LOGOUT_START";
export  const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export  const LOGOUT_FAIL = "LOGOUT_FAIL";

export  const RESSET_PASSWORD_START = "RESSET_PASSWORD_START";
export  const RESSET_PASSWORD_SUCCESS = "RESSET_PASSWORD_SUCCESS";
export  const RESSET_PASSWORD_FAIL = "RESSET_PASSWORD_FAIL";

export  const GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_SIN_TART";
export  const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export  const GOOGLE_SIGN_IN_FAIL = "GOOGLE_SIGN_IN_FAIL";

export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";